# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385ea2043c1afd4eab39e0baac5ab38ace73ade376ab4dc75a803f65e823ab16a0ecae44655c226334987e642044ed10f0914e704efb580f0303f6aff8286f42

test:
  secret_key_base: bf73fb44c647bed6854786fc94f414c619056578263202e38270a777e38e4c5608b60bf04bb39519799c4ba7039c96228fd2f445e7e0eabca6083d842695684b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
